services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: camup_app
    volumes:
      - ./src:/var/www
      - /var/www/node_modules  # Prevents conflict with host node_modules
    working_dir: /var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: camup_web
    ports:
      - "8010:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: camup_vite
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: camup_db
    environment:
      MYSQL_DATABASE: camup
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
